export const EMPTY_CART = {
	id: null,
	taxes: null,
	tax_total: 0,
	tax_included_total: 0,
	sub_total: 0,
	shipping: {},
	shipment_total: 0,
	shipment_rating: null,
	shipment_price: 0,
	shipment_discount: 0,
	promotion_ids: [],
	items: [],
	item_tax: 0,
	item_shipment_weight: 0,
	item_quantity: 0,
	item_discount: 0,
	guest: true,
	grand_total: 0,
	giftcard_total: 0,
	discounts: null,
	discount_total: 0,
	currency: 'USD',
	capture_total: 0,
	auth_total: 0,
	account_logged_in: null,
	checkout_url: null
}
